# this file uses prebuilt image in dockerhub
services:
  jekyll:
    build: 
      context: .
      args:
        GROUPID: 1000
        GROUPNAME: jekyll
        USERID: 1000
        USERNAME: jekyll
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
